%FADD	Compute element-wise modular addtion
%
%	FADD(F, X, Y)   is the element-wise modular addition of vectors X and Y.
%	with:
%		 F: Field
%		 X: Vector of Element
%		 Y: Vector of Element
%
%	FADD(F, A, B)   is the element-wise modular addition of matrix A and B.
%	with:
%		 F: Field
%		 A: Matrix of Element
%		 B: Matrix of Element
%
%	FADD(F, X, alpha, Y)   is the element-wise modular addition: (X+alpha(Y)) mod F
%	with:
%		 F: Field
%		 X: Vector of Element
%		 alpha: Element
%		 Y: Vector of Element
%
%	FADD(F, A, alpha, B)   is the element-wise modular addition: (A+alpha(B)) mod F
%	with:
%		 F: Field
%		 A: Matrix of Element
%		 alpha: Element
%		 B: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
