%FADD	Compute element-wise modular addtion
%
%	FADD(p, X, Y)   is the element-wise modular addition of vectors X and Y.
%	with:
%		 p: Element of Field 0x16f83e0
%		 X: Vector
%		 Y: Vector
%
%	FADD(p, A, B)   is the element-wise modular addition of matrix A and B.
%	with:
%		 p: Element of Field 0x16fa6d0
%		 A: Matrix
%		 B: Matrix
%
%	FADD(p, X, alpha, Y)   is the element-wise modular addition: (X+alpha(Y)) mod p
%	with:
%		 p: Element of Field 0x16fcce0
%		 X: Vector
%		 alpha: Element of Field 0x16fcce0
%		 Y: Vector
%
%	FADD(p, A, alpha, B)   is the element-wise modular addition: (A+alpha(B)) mod p
%	with:
%		 p: Element of Field 0x16ffaf0
%		 A: Matrix
%		 alpha: Element of Field 0x16ffaf0
%		 B: Matrix
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the ffinter tool
%
%   This file is part of the library FFLAS-FFPACK.
%
%   FFLAS-FFPACK is free software: you can redistribute it and/or modify
%   it under the terms of the  GNU Lesser General Public
%   License as published by the Free Software Foundation; either
%   version 2.1 of the License, or (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%   Lesser General Public License for more details.
%
%   You should have received a copy of the GNU Lesser General Public
%   License along with this library; if not, write to the Free Software
%   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


