%FAXPY	Compute faxpy modular expression (alpha * X + Y) mod F
%
%	FAXPY(F, alpha, X, Y)   
%	with:
%		 F: Field
%		 alpha: Element
%		 X: Vector of Element
%		 Y: Vector of Element
%
%	FAXPY(F, alpha, A, B)   
%	with:
%		 F: Field
%		 alpha: Element
%		 A: Matrix of Element
%		 B: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
