%FDOT	Compute modular dot product between vectors
%
%	FDOT(F, X, Y)   
%	with:
%		 F: Field
%		 X: Vector of Element
%		 Y: Vector of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
