/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 *     Generated by the 'ffinterg' tool (v0.4)
 *
 * ========LICENCE========
 * This file is part of the library FFLAS-FFPACK.
 *
 * FFLAS-FFPACK is free software: you can redistribute it and/or modify
 * it under the terms of the  GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 * ========LICENCE========
 */

#include "ffintert_matlab.h"
using namespace ffintert;

int32_t ff_fdot(int32_t, size_t, const int32_t*, size_t, int32_t*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
int64_t ff_fdot(int64_t, size_t, const int64_t*, size_t, int64_t*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
Integer ff_fdot(Integer, size_t, const Integer*, size_t, Integer*, size_t);
float ff_fdot(float, size_t, const float*, size_t, float*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
double ff_fdot(double, size_t, const double*, size_t, double*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);



/* -------------------------------------------------------------------------- */

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
  if (((((nrhs == 3) && isElement<int32_t>(prhs[0])) && isVector<int32_t>(prhs[1])) && isVector<int32_t>(prhs[2]))) {
    int32_t p = getElement<int32_t>(prhs[0]);
    Vector<int32_t> X = getVector<int32_t>(prhs[1]);
    Vector<int32_t> Y = getVector<int32_t>(prhs[2]);
    size_t n = length(X);
    check(n, length(Y), "n");
    const int32_t* _tmp_0 = constptr(X);
    size_t _tmp_1 = st(X);
    int32_t* _tmp_2 = ptr(Y);
    size_t _tmp_3 = st(Y);
    int32_t Z = ff_fdot(p, n, _tmp_0, _tmp_1, _tmp_2, _tmp_3);
    createAndSetElement(plhs[0], Z);
  } else if (((((nrhs == 3) && isElement<int64_t>(prhs[0])) && isVector<int64_t>(prhs[1])) && isVector<int64_t>(prhs[2]))) {
    int64_t p = getElement<int64_t>(prhs[0]);
    Vector<int64_t> X = getVector<int64_t>(prhs[1]);
    Vector<int64_t> Y = getVector<int64_t>(prhs[2]);
    size_t n = length(X);
    check(n, length(Y), "n");
    const int64_t* _tmp_0 = constptr(X);
    size_t _tmp_1 = st(X);
    int64_t* _tmp_2 = ptr(Y);
    size_t _tmp_3 = st(Y);
    int64_t Z = ff_fdot(p, n, _tmp_0, _tmp_1, _tmp_2, _tmp_3);
    createAndSetElement(plhs[0], Z);
  } else if (((((nrhs == 3) && isElement<float>(prhs[0])) && isVector<float>(prhs[1])) && isVector<float>(prhs[2]))) {
    float p = getElement<float>(prhs[0]);
    Vector<float> X = getVector<float>(prhs[1]);
    Vector<float> Y = getVector<float>(prhs[2]);
    size_t n = length(X);
    check(n, length(Y), "n");
    const float* _tmp_0 = constptr(X);
    size_t _tmp_1 = st(X);
    float* _tmp_2 = ptr(Y);
    size_t _tmp_3 = st(Y);
    float Z = ff_fdot(p, n, _tmp_0, _tmp_1, _tmp_2, _tmp_3);
    createAndSetElement(plhs[0], Z);
  } else if (((((nrhs == 3) && isElement<double>(prhs[0])) && isVector<double>(prhs[1])) && isVector<double>(prhs[2]))) {
    double p = getElement<double>(prhs[0]);
    Vector<double> X = getVector<double>(prhs[1]);
    Vector<double> Y = getVector<double>(prhs[2]);
    size_t n = length(X);
    check(n, length(Y), "n");
    const double* _tmp_0 = constptr(X);
    size_t _tmp_1 = st(X);
    double* _tmp_2 = ptr(Y);
    size_t _tmp_3 = st(Y);
    double Z = ff_fdot(p, n, _tmp_0, _tmp_1, _tmp_2, _tmp_3);
    createAndSetElement(plhs[0], Z);
  } else {
    error("wrong arguments types (or number) for routine: fdot.");
  }
}

