%FEQUAL	Test equality.
%
%	FEQUAL(F, X, Y)   true if mod(X,F) == mod(Y,F).
%	with:
%		 F: Field
%		 X: Vector of Element
%		 Y: Vector of Element
%
%	FEQUAL(F, A, B)   true if mod(A,F) == mod(B,F)
%	with:
%		 F: Field
%		 A: Matrix of Element
%		 B: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
