%FGEMM	General Matrix-Matrix multiplication
%
%	FGEMM(F, alpha, A, B, beta, C)   
%	with:
%		 F: Field
%		 alpha: Element
%		 A: Matrix of Element
%		 B: Matrix of Element
%		 beta: Element
%		 C: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
