/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 *     Generated by the 'ffinterg' tool (v0.4)
 *
 * ========LICENCE========
 * This file is part of the library FFLAS-FFPACK.
 *
 * FFLAS-FFPACK is free software: you can redistribute it and/or modify
 * it under the terms of the  GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 * ========LICENCE========
 */

#include "ffintert_matlab.h"
using namespace ffintert;

void ff_fgemm(int32_t, FFLAS_C_TRANSPOSE, FFLAS_C_TRANSPOSE, size_t, size_t, size_t, int32_t, const int32_t*, size_t, const int32_t*, size_t, int32_t, int32_t*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_fgemm(int64_t, FFLAS_C_TRANSPOSE, FFLAS_C_TRANSPOSE, size_t, size_t, size_t, int64_t, const int64_t*, size_t, const int64_t*, size_t, int64_t, int64_t*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_fgemm(Integer, FFLAS_C_TRANSPOSE, FFLAS_C_TRANSPOSE, size_t, size_t, size_t, Integer, const Integer*, size_t, const Integer*, size_t, Integer, Integer*, size_t);
void ff_fgemm(float, FFLAS_C_TRANSPOSE, FFLAS_C_TRANSPOSE, size_t, size_t, size_t, float, const float*, size_t, const float*, size_t, float, float*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_fgemm(double, FFLAS_C_TRANSPOSE, FFLAS_C_TRANSPOSE, size_t, size_t, size_t, double, const double*, size_t, const double*, size_t, double, double*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);



/* -------------------------------------------------------------------------- */

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
  if ((((((((nrhs == 6) && isElement<int32_t>(prhs[0])) && isElement<int32_t>(prhs[1])) && isMatrix<int32_t>(prhs[2])) && isMatrix<int32_t>(prhs[3])) && isElement<int32_t>(prhs[4])) && isMatrix<int32_t>(prhs[5]))) {
    int32_t p = getElement<int32_t>(prhs[0]);
    int32_t alpha = getElement<int32_t>(prhs[1]);
    Matrix<int32_t> A = getMatrix<int32_t>(prhs[2]);
    Matrix<int32_t> B = getMatrix<int32_t>(prhs[3]);
    int32_t beta = getElement<int32_t>(prhs[4]);
    Matrix<int32_t> C = duplicateMatrix<int32_t>(prhs[5], plhs[0]);
    size_t m = rows(A);
    check(m, rows(C), "m");
    size_t n = cols(B);
    check(n, cols(C), "n");
    size_t k = cols(A);
    check(k, rows(B), "k");
    FFLAS_C_TRANSPOSE _tmp_0 = FflasNoTrans;
    FFLAS_C_TRANSPOSE _tmp_1 = FflasNoTrans;
    const int32_t* _tmp_2 = constptr(B);
    size_t _tmp_3 = ld(B);
    const int32_t* _tmp_4 = constptr(A);
    size_t _tmp_5 = ld(A);
    int32_t* _tmp_6 = ptr(C);
    size_t _tmp_7 = ld(C);
    ff_fgemm(p, _tmp_0, _tmp_1, n, m, k, alpha, _tmp_2, _tmp_3, _tmp_4, _tmp_5, beta, _tmp_6, _tmp_7);
  } else if ((((((((nrhs == 6) && isElement<int64_t>(prhs[0])) && isElement<int64_t>(prhs[1])) && isMatrix<int64_t>(prhs[2])) && isMatrix<int64_t>(prhs[3])) && isElement<int64_t>(prhs[4])) && isMatrix<int64_t>(prhs[5]))) {
    int64_t p = getElement<int64_t>(prhs[0]);
    int64_t alpha = getElement<int64_t>(prhs[1]);
    Matrix<int64_t> A = getMatrix<int64_t>(prhs[2]);
    Matrix<int64_t> B = getMatrix<int64_t>(prhs[3]);
    int64_t beta = getElement<int64_t>(prhs[4]);
    Matrix<int64_t> C = duplicateMatrix<int64_t>(prhs[5], plhs[0]);
    size_t m = rows(A);
    check(m, rows(C), "m");
    size_t n = cols(B);
    check(n, cols(C), "n");
    size_t k = cols(A);
    check(k, rows(B), "k");
    FFLAS_C_TRANSPOSE _tmp_0 = FflasNoTrans;
    FFLAS_C_TRANSPOSE _tmp_1 = FflasNoTrans;
    const int64_t* _tmp_2 = constptr(B);
    size_t _tmp_3 = ld(B);
    const int64_t* _tmp_4 = constptr(A);
    size_t _tmp_5 = ld(A);
    int64_t* _tmp_6 = ptr(C);
    size_t _tmp_7 = ld(C);
    ff_fgemm(p, _tmp_0, _tmp_1, n, m, k, alpha, _tmp_2, _tmp_3, _tmp_4, _tmp_5, beta, _tmp_6, _tmp_7);
  } else if ((((((((nrhs == 6) && isElement<float>(prhs[0])) && isElement<float>(prhs[1])) && isMatrix<float>(prhs[2])) && isMatrix<float>(prhs[3])) && isElement<float>(prhs[4])) && isMatrix<float>(prhs[5]))) {
    float p = getElement<float>(prhs[0]);
    float alpha = getElement<float>(prhs[1]);
    Matrix<float> A = getMatrix<float>(prhs[2]);
    Matrix<float> B = getMatrix<float>(prhs[3]);
    float beta = getElement<float>(prhs[4]);
    Matrix<float> C = duplicateMatrix<float>(prhs[5], plhs[0]);
    size_t m = rows(A);
    check(m, rows(C), "m");
    size_t n = cols(B);
    check(n, cols(C), "n");
    size_t k = cols(A);
    check(k, rows(B), "k");
    FFLAS_C_TRANSPOSE _tmp_0 = FflasNoTrans;
    FFLAS_C_TRANSPOSE _tmp_1 = FflasNoTrans;
    const float* _tmp_2 = constptr(B);
    size_t _tmp_3 = ld(B);
    const float* _tmp_4 = constptr(A);
    size_t _tmp_5 = ld(A);
    float* _tmp_6 = ptr(C);
    size_t _tmp_7 = ld(C);
    ff_fgemm(p, _tmp_0, _tmp_1, n, m, k, alpha, _tmp_2, _tmp_3, _tmp_4, _tmp_5, beta, _tmp_6, _tmp_7);
  } else if ((((((((nrhs == 6) && isElement<double>(prhs[0])) && isElement<double>(prhs[1])) && isMatrix<double>(prhs[2])) && isMatrix<double>(prhs[3])) && isElement<double>(prhs[4])) && isMatrix<double>(prhs[5]))) {
    double p = getElement<double>(prhs[0]);
    double alpha = getElement<double>(prhs[1]);
    Matrix<double> A = getMatrix<double>(prhs[2]);
    Matrix<double> B = getMatrix<double>(prhs[3]);
    double beta = getElement<double>(prhs[4]);
    Matrix<double> C = duplicateMatrix<double>(prhs[5], plhs[0]);
    size_t m = rows(A);
    check(m, rows(C), "m");
    size_t n = cols(B);
    check(n, cols(C), "n");
    size_t k = cols(A);
    check(k, rows(B), "k");
    FFLAS_C_TRANSPOSE _tmp_0 = FflasNoTrans;
    FFLAS_C_TRANSPOSE _tmp_1 = FflasNoTrans;
    const double* _tmp_2 = constptr(B);
    size_t _tmp_3 = ld(B);
    const double* _tmp_4 = constptr(A);
    size_t _tmp_5 = ld(A);
    double* _tmp_6 = ptr(C);
    size_t _tmp_7 = ld(C);
    ff_fgemm(p, _tmp_0, _tmp_1, n, m, k, alpha, _tmp_2, _tmp_3, _tmp_4, _tmp_5, beta, _tmp_6, _tmp_7);
  } else {
    error("wrong arguments types (or number) for routine: fgemm.");
  }
}

