/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 *     Generated by the 'ffinterg' tool (v0.4)
 *
 * ========LICENCE========
 * This file is part of the library FFLAS-FFPACK.
 *
 * FFLAS-FFPACK is free software: you can redistribute it and/or modify
 * it under the terms of the  GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 * ========LICENCE========
 */

#include "ffintert_matlab.h"
using namespace ffintert;

void ff_fgemv(int32_t, FFLAS_C_TRANSPOSE, size_t, size_t, int32_t, const int32_t*, size_t, const int32_t*, size_t, int32_t, int32_t*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_fgemv(int64_t, FFLAS_C_TRANSPOSE, size_t, size_t, int64_t, const int64_t*, size_t, const int64_t*, size_t, int64_t, int64_t*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_fgemv(Integer, FFLAS_C_TRANSPOSE, size_t, size_t, Integer, const Integer*, size_t, const Integer*, size_t, Integer, Integer*, size_t);
void ff_fgemv(float, FFLAS_C_TRANSPOSE, size_t, size_t, float, const float*, size_t, const float*, size_t, float, float*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_fgemv(double, FFLAS_C_TRANSPOSE, size_t, size_t, double, const double*, size_t, const double*, size_t, double, double*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);



/* -------------------------------------------------------------------------- */

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
  if ((((((((nrhs == 6) && isElement<int32_t>(prhs[0])) && isElement<int32_t>(prhs[1])) && isMatrix<int32_t>(prhs[2])) && isVector<int32_t>(prhs[3])) && isElement<int32_t>(prhs[4])) && isVector<int32_t>(prhs[5]))) {
    int32_t p = getElement<int32_t>(prhs[0]);
    int32_t alpha = getElement<int32_t>(prhs[1]);
    Matrix<int32_t> A = getMatrix<int32_t>(prhs[2]);
    Vector<int32_t> X = getVector<int32_t>(prhs[3]);
    int32_t beta = getElement<int32_t>(prhs[4]);
    Vector<int32_t> Y = duplicateVector<int32_t>(prhs[5], plhs[0]);
    size_t m = rows(A);
    size_t n = cols(A);
    check(n, length(X), "n");
    check(m, length(Y), "m");
    FFLAS_C_TRANSPOSE _tmp_0 = FflasTrans;
    const int32_t* _tmp_1 = constptr(A);
    size_t _tmp_2 = ld(A);
    const int32_t* _tmp_3 = constptr(X);
    size_t _tmp_4 = st(X);
    int32_t* _tmp_5 = ptr(Y);
    size_t _tmp_6 = st(Y);
    ff_fgemv(p, _tmp_0, n, m, alpha, _tmp_1, _tmp_2, _tmp_3, _tmp_4, beta, _tmp_5, _tmp_6);
  } else if ((((((((nrhs == 6) && isElement<int64_t>(prhs[0])) && isElement<int64_t>(prhs[1])) && isMatrix<int64_t>(prhs[2])) && isVector<int64_t>(prhs[3])) && isElement<int64_t>(prhs[4])) && isVector<int64_t>(prhs[5]))) {
    int64_t p = getElement<int64_t>(prhs[0]);
    int64_t alpha = getElement<int64_t>(prhs[1]);
    Matrix<int64_t> A = getMatrix<int64_t>(prhs[2]);
    Vector<int64_t> X = getVector<int64_t>(prhs[3]);
    int64_t beta = getElement<int64_t>(prhs[4]);
    Vector<int64_t> Y = duplicateVector<int64_t>(prhs[5], plhs[0]);
    size_t m = rows(A);
    size_t n = cols(A);
    check(n, length(X), "n");
    check(m, length(Y), "m");
    FFLAS_C_TRANSPOSE _tmp_0 = FflasTrans;
    const int64_t* _tmp_1 = constptr(A);
    size_t _tmp_2 = ld(A);
    const int64_t* _tmp_3 = constptr(X);
    size_t _tmp_4 = st(X);
    int64_t* _tmp_5 = ptr(Y);
    size_t _tmp_6 = st(Y);
    ff_fgemv(p, _tmp_0, n, m, alpha, _tmp_1, _tmp_2, _tmp_3, _tmp_4, beta, _tmp_5, _tmp_6);
  } else if ((((((((nrhs == 6) && isElement<float>(prhs[0])) && isElement<float>(prhs[1])) && isMatrix<float>(prhs[2])) && isVector<float>(prhs[3])) && isElement<float>(prhs[4])) && isVector<float>(prhs[5]))) {
    float p = getElement<float>(prhs[0]);
    float alpha = getElement<float>(prhs[1]);
    Matrix<float> A = getMatrix<float>(prhs[2]);
    Vector<float> X = getVector<float>(prhs[3]);
    float beta = getElement<float>(prhs[4]);
    Vector<float> Y = duplicateVector<float>(prhs[5], plhs[0]);
    size_t m = rows(A);
    size_t n = cols(A);
    check(n, length(X), "n");
    check(m, length(Y), "m");
    FFLAS_C_TRANSPOSE _tmp_0 = FflasTrans;
    const float* _tmp_1 = constptr(A);
    size_t _tmp_2 = ld(A);
    const float* _tmp_3 = constptr(X);
    size_t _tmp_4 = st(X);
    float* _tmp_5 = ptr(Y);
    size_t _tmp_6 = st(Y);
    ff_fgemv(p, _tmp_0, n, m, alpha, _tmp_1, _tmp_2, _tmp_3, _tmp_4, beta, _tmp_5, _tmp_6);
  } else if ((((((((nrhs == 6) && isElement<double>(prhs[0])) && isElement<double>(prhs[1])) && isMatrix<double>(prhs[2])) && isVector<double>(prhs[3])) && isElement<double>(prhs[4])) && isVector<double>(prhs[5]))) {
    double p = getElement<double>(prhs[0]);
    double alpha = getElement<double>(prhs[1]);
    Matrix<double> A = getMatrix<double>(prhs[2]);
    Vector<double> X = getVector<double>(prhs[3]);
    double beta = getElement<double>(prhs[4]);
    Vector<double> Y = duplicateVector<double>(prhs[5], plhs[0]);
    size_t m = rows(A);
    size_t n = cols(A);
    check(n, length(X), "n");
    check(m, length(Y), "m");
    FFLAS_C_TRANSPOSE _tmp_0 = FflasTrans;
    const double* _tmp_1 = constptr(A);
    size_t _tmp_2 = ld(A);
    const double* _tmp_3 = constptr(X);
    size_t _tmp_4 = st(X);
    double* _tmp_5 = ptr(Y);
    size_t _tmp_6 = st(Y);
    ff_fgemv(p, _tmp_0, n, m, alpha, _tmp_1, _tmp_2, _tmp_3, _tmp_4, beta, _tmp_5, _tmp_6);
  } else {
    error("wrong arguments types (or number) for routine: fgemv.");
  }
}

