%FGEMV	General Matrix Vector modular multiplication.
%
%	FGEMV(F, alpha, A, X, beta, Y)   
%	with:
%		 F: Field
%		 alpha: Element
%		 A: Matrix of Element
%		 X: Vector of Element
%		 beta: Element
%		 Y: Vector of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
