/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_matlab.h"
int ff_fgemm_0(double, ffintert::FlagTrans, ffintert::FlagTrans, size_t, size_t, size_t, double, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t, double, ffintert::Matrix<double>, size_t);



/* -------------------------------------------------------------------------- */

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
  if ((((((((nrhs == 6) && ffintert::isField(prhs[0])) && ffintert::isElement(prhs[1])) && (ffintert::isMatrix(prhs[2]) && ffintert::isElement(prhs[2]))) && (ffintert::isMatrix(prhs[3]) && ffintert::isElement(prhs[3]))) && ffintert::isElement(prhs[4])) && (ffintert::isMatrix(prhs[5]) && ffintert::isElement(prhs[5])))) {
    double F = ffintert::getField(prhs[0]);
    double alpha = ffintert::getElement(prhs[1]);
    ffintert::Matrix<double> A = ffintert::getMatrix(prhs[2]);
    ffintert::Matrix<double> B = ffintert::getMatrix(prhs[3]);
    double beta = ffintert::getElement(prhs[4]);
    ffintert::Matrix<double> C = ffintert::duplicateMatrix(prhs[5], plhs[0]);
    size_t m = ffintert::rows(A);
    ffintert::check(m, ffintert::rows(C), "m");
    size_t n = ffintert::cols(B);
    ffintert::check(n, ffintert::cols(C), "n");
    size_t k = ffintert::cols(A);
    ffintert::check(k, ffintert::rows(B), "k");
    ffintert::FlagTrans _tmp_0 = ffintert::NoTrans;
    ffintert::FlagTrans _tmp_1 = ffintert::NoTrans;
    size_t _tmp_2 = ffintert::ld(B);
    size_t _tmp_3 = ffintert::ld(A);
    size_t _tmp_4 = ffintert::ld(C);
    ff_fgemm_0(F, _tmp_0, _tmp_1, n, m, k, alpha, B, _tmp_2, A, _tmp_3, beta, C, _tmp_4);
  } else {
    ffintert::error("wrong arguments types (or number) for routine: fgemm.");
  }  
}

