/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 *     Generated by the 'ffinterg' tool (v0.4)
 *
 * ========LICENCE========
 * This file is part of the library FFLAS-FFPACK.
 *
 * FFLAS-FFPACK is free software: you can redistribute it and/or modify
 * it under the terms of the  GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 * ========LICENCE========
 */

#include "ffintert_matlab.h"
using namespace ffintert;

void ff_fger(int32_t, size_t, size_t, int32_t, int32_t*, size_t, int32_t*, size_t, int32_t*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_fger(int64_t, size_t, size_t, int64_t, int64_t*, size_t, int64_t*, size_t, int64_t*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_fger(float, size_t, size_t, float, float*, size_t, float*, size_t, float*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_fger(double, size_t, size_t, double, double*, size_t, double*, size_t, double*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);



/* -------------------------------------------------------------------------- */

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
  if (((((((nrhs == 5) && isElement<int32_t>(prhs[0])) && isElement<int32_t>(prhs[1])) && isVector<int32_t>(prhs[2])) && isVector<int32_t>(prhs[3])) && isMatrix<int32_t>(prhs[4]))) {
    int32_t p = getElement<int32_t>(prhs[0]);
    int32_t alpha = getElement<int32_t>(prhs[1]);
    Vector<int32_t> X = getVector<int32_t>(prhs[2]);
    Vector<int32_t> Y = getVector<int32_t>(prhs[3]);
    Matrix<int32_t> A = duplicateMatrix<int32_t>(prhs[4], plhs[0]);
    size_t m = length(X);
    size_t n = length(Y);
    check(m, rows(A), "m");
    check(n, cols(A), "n");
    int32_t* _tmp_0 = ptr(Y);
    size_t _tmp_1 = st(Y);
    int32_t* _tmp_2 = ptr(X);
    size_t _tmp_3 = st(X);
    int32_t* _tmp_4 = ptr(A);
    size_t _tmp_5 = ld(A);
    ff_fger(p, n, m, alpha, _tmp_0, _tmp_1, _tmp_2, _tmp_3, _tmp_4, _tmp_5);
  } else if (((((((nrhs == 5) && isElement<int64_t>(prhs[0])) && isElement<int64_t>(prhs[1])) && isVector<int64_t>(prhs[2])) && isVector<int64_t>(prhs[3])) && isMatrix<int64_t>(prhs[4]))) {
    int64_t p = getElement<int64_t>(prhs[0]);
    int64_t alpha = getElement<int64_t>(prhs[1]);
    Vector<int64_t> X = getVector<int64_t>(prhs[2]);
    Vector<int64_t> Y = getVector<int64_t>(prhs[3]);
    Matrix<int64_t> A = duplicateMatrix<int64_t>(prhs[4], plhs[0]);
    size_t m = length(X);
    size_t n = length(Y);
    check(m, rows(A), "m");
    check(n, cols(A), "n");
    int64_t* _tmp_0 = ptr(Y);
    size_t _tmp_1 = st(Y);
    int64_t* _tmp_2 = ptr(X);
    size_t _tmp_3 = st(X);
    int64_t* _tmp_4 = ptr(A);
    size_t _tmp_5 = ld(A);
    ff_fger(p, n, m, alpha, _tmp_0, _tmp_1, _tmp_2, _tmp_3, _tmp_4, _tmp_5);
  } else if (((((((nrhs == 5) && isElement<float>(prhs[0])) && isElement<float>(prhs[1])) && isVector<float>(prhs[2])) && isVector<float>(prhs[3])) && isMatrix<float>(prhs[4]))) {
    float p = getElement<float>(prhs[0]);
    float alpha = getElement<float>(prhs[1]);
    Vector<float> X = getVector<float>(prhs[2]);
    Vector<float> Y = getVector<float>(prhs[3]);
    Matrix<float> A = duplicateMatrix<float>(prhs[4], plhs[0]);
    size_t m = length(X);
    size_t n = length(Y);
    check(m, rows(A), "m");
    check(n, cols(A), "n");
    float* _tmp_0 = ptr(Y);
    size_t _tmp_1 = st(Y);
    float* _tmp_2 = ptr(X);
    size_t _tmp_3 = st(X);
    float* _tmp_4 = ptr(A);
    size_t _tmp_5 = ld(A);
    ff_fger(p, n, m, alpha, _tmp_0, _tmp_1, _tmp_2, _tmp_3, _tmp_4, _tmp_5);
  } else if (((((((nrhs == 5) && isElement<double>(prhs[0])) && isElement<double>(prhs[1])) && isVector<double>(prhs[2])) && isVector<double>(prhs[3])) && isMatrix<double>(prhs[4]))) {
    double p = getElement<double>(prhs[0]);
    double alpha = getElement<double>(prhs[1]);
    Vector<double> X = getVector<double>(prhs[2]);
    Vector<double> Y = getVector<double>(prhs[3]);
    Matrix<double> A = duplicateMatrix<double>(prhs[4], plhs[0]);
    size_t m = length(X);
    size_t n = length(Y);
    check(m, rows(A), "m");
    check(n, cols(A), "n");
    double* _tmp_0 = ptr(Y);
    size_t _tmp_1 = st(Y);
    double* _tmp_2 = ptr(X);
    size_t _tmp_3 = st(X);
    double* _tmp_4 = ptr(A);
    size_t _tmp_5 = ld(A);
    ff_fger(p, n, m, alpha, _tmp_0, _tmp_1, _tmp_2, _tmp_3, _tmp_4, _tmp_5);
  } else {
    error("wrong arguments types (or number) for routine: fger.");
  }
}

