/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_matlab.h"
int ff_fger_0(double, size_t, size_t, double, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t, ffintert::Matrix<double>, size_t);



/* -------------------------------------------------------------------------- */

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
  if (((((((nrhs == 5) && ffintert::isField(prhs[0])) && ffintert::isElement(prhs[1])) && (ffintert::isVector(prhs[2]) && ffintert::isElement(prhs[2]))) && (ffintert::isVector(prhs[3]) && ffintert::isElement(prhs[3]))) && (ffintert::isMatrix(prhs[4]) && ffintert::isElement(prhs[4])))) {
    double F = ffintert::getField(prhs[0]);
    double alpha = ffintert::getElement(prhs[1]);
    ffintert::Vector<double> X = ffintert::getVector(prhs[2]);
    ffintert::Vector<double> Y = ffintert::getVector(prhs[3]);
    ffintert::Matrix<double> A = ffintert::duplicateMatrix(prhs[4], plhs[0]);
    size_t m = ffintert::length(X);
    size_t n = ffintert::length(Y);
    ffintert::check(m, ffintert::rows(A), "m");
    ffintert::check(n, ffintert::cols(A), "n");
    size_t _tmp_0 = ffintert::st(Y);
    size_t _tmp_1 = ffintert::st(X);
    size_t _tmp_2 = ffintert::ld(A);
    ff_fger_0(F, n, m, alpha, Y, _tmp_0, X, _tmp_1, A, _tmp_2);
  } else {
    ffintert::error("wrong arguments types (or number) for routine: fger.");
  }  
}

