%FGER	Rank one update of a general matrix.
%
%	FGER(F, alpha, X, Y, A)   
%	with:
%		 F: Field
%		 alpha: Element
%		 X: Vector of Element
%		 Y: Vector of Element
%		 A: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
