%FISZERO	True is all elements are zero.
%
%	FISZERO(F, X)   true if all elements of X are zeros.
%	with:
%		 F: Field
%		 X: Vector of Element
%
%	FISZERO(F, A)   true if all elements of A are zeros
%	with:
%		 F: Field
%		 A: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
