%FNEG	Compute element-wise modular opposite
%
%	FNEG(F, X)   is the modular opposite of the elements of X
%	with:
%		 F: Field
%		 X: Vector of Element
%
%	FNEG(F, A)   is the modular opposite of the elements of A
%	with:
%		 F: Field
%		 A: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
