%FREDUCE	Compute modular reduction
%
%	FREDUCE(F, X)   is the modular reduction of elements the of X.
%	with:
%		 F: Field
%		 X: Vector of Element
%
%	FREDUCE(F, A)   is the modular reduction of the elements of A.
%	with:
%		 F: Field
%		 A: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
