%FSCAL	Compute modular scalar multiplication
%
%	FSCAL(F, alpha, X)   is the modular scalar multiplication alpha * X
%	with:
%		 F: Field
%		 alpha: Element
%		 X: Vector of Element
%
%	FSCAL(F, alpha, A)   is the modular scalar multiplication alpha * A
%	with:
%		 F: Field
%		 alpha: Element
%		 A: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
