%FSUB	Compute element-wise modular subtraction
%
%	FSUB(F, X, Y)   is the element-wise modular subtraction of vectors X and Y.
%	with:
%		 F: Field
%		 X: Vector of Element
%		 Y: Vector of Element
%
%	FSUB(F, A, B)   is the element-wise modular subtraction of matrices A and B.
%	with:
%		 F: Field
%		 A: Matrix of Element
%		 B: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
