%FTRSV	Triangular system solve with vector.
%
%	FTRSV(F, U, D, A, X)   
%	with:
%		 F: Field
%		 U: Uplo
%		 D: Diag
%		 A: Matrix of Element
%		 X: Vector of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
