/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 *     Generated by the 'ffinterg' tool (v0.4)
 *
 * ========LICENCE========
 * This file is part of the library FFLAS-FFPACK.
 *
 * FFLAS-FFPACK is free software: you can redistribute it and/or modify
 * it under the terms of the  GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 * ========LICENCE========
 */

#include "ffintert_matlab.h"
using namespace ffintert;

void ff_ftrsm(int32_t, FFLAS_C_SIDE, FFLAS_C_UPLO, FFLAS_C_TRANSPOSE, FFLAS_C_DIAG, size_t, size_t, int32_t, const int32_t*, size_t, int32_t*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_ftrsm(int64_t, FFLAS_C_SIDE, FFLAS_C_UPLO, FFLAS_C_TRANSPOSE, FFLAS_C_DIAG, size_t, size_t, int64_t, const int64_t*, size_t, int64_t*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_ftrsm(Integer, FFLAS_C_SIDE, FFLAS_C_UPLO, FFLAS_C_TRANSPOSE, FFLAS_C_DIAG, size_t, size_t, Integer, const Integer*, size_t, Integer*, size_t);
void ff_ftrsm(float, FFLAS_C_SIDE, FFLAS_C_UPLO, FFLAS_C_TRANSPOSE, FFLAS_C_DIAG, size_t, size_t, float, const float*, size_t, float*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_ftrsm(double, FFLAS_C_SIDE, FFLAS_C_UPLO, FFLAS_C_TRANSPOSE, FFLAS_C_DIAG, size_t, size_t, double, const double*, size_t, double*, size_t, FP_C_RP = FP_C_RP_ModularBalanced);



/* -------------------------------------------------------------------------- */

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
  if (((((((((nrhs == 7) && isElement<int32_t>(prhs[0])) && isSide(prhs[1])) && isUplo(prhs[2])) && isDiag(prhs[3])) && isElement<int32_t>(prhs[4])) && isMatrix<int32_t>(prhs[5])) && isMatrix<int32_t>(prhs[6]))) {
    int32_t p = getElement<int32_t>(prhs[0]);
    FFLAS_C_SIDE S = getSide(prhs[1]);
    FFLAS_C_UPLO U = getUplo(prhs[2]);
    FFLAS_C_DIAG D = getDiag(prhs[3]);
    int32_t alpha = getElement<int32_t>(prhs[4]);
    Matrix<int32_t> A = getMatrix<int32_t>(prhs[5]);
    Matrix<int32_t> B = duplicateMatrix<int32_t>(prhs[6], plhs[0]);
    size_t m = rows(B);
    size_t n = cols(B);
    FFLAS_C_SIDE _tmp_0 = invert(S);
    FFLAS_C_UPLO _tmp_1 = invert(U);
    FFLAS_C_TRANSPOSE _tmp_2 = FflasNoTrans;
    const int32_t* _tmp_3 = constptr(A);
    size_t _tmp_4 = ld(A);
    int32_t* _tmp_5 = ptr(B);
    size_t _tmp_6 = ld(B);
    ff_ftrsm(p, _tmp_0, _tmp_1, _tmp_2, D, n, m, alpha, _tmp_3, _tmp_4, _tmp_5, _tmp_6);
  } else if (((((((((nrhs == 7) && isElement<int64_t>(prhs[0])) && isSide(prhs[1])) && isUplo(prhs[2])) && isDiag(prhs[3])) && isElement<int64_t>(prhs[4])) && isMatrix<int64_t>(prhs[5])) && isMatrix<int64_t>(prhs[6]))) {
    int64_t p = getElement<int64_t>(prhs[0]);
    FFLAS_C_SIDE S = getSide(prhs[1]);
    FFLAS_C_UPLO U = getUplo(prhs[2]);
    FFLAS_C_DIAG D = getDiag(prhs[3]);
    int64_t alpha = getElement<int64_t>(prhs[4]);
    Matrix<int64_t> A = getMatrix<int64_t>(prhs[5]);
    Matrix<int64_t> B = duplicateMatrix<int64_t>(prhs[6], plhs[0]);
    size_t m = rows(B);
    size_t n = cols(B);
    FFLAS_C_SIDE _tmp_0 = invert(S);
    FFLAS_C_UPLO _tmp_1 = invert(U);
    FFLAS_C_TRANSPOSE _tmp_2 = FflasNoTrans;
    const int64_t* _tmp_3 = constptr(A);
    size_t _tmp_4 = ld(A);
    int64_t* _tmp_5 = ptr(B);
    size_t _tmp_6 = ld(B);
    ff_ftrsm(p, _tmp_0, _tmp_1, _tmp_2, D, n, m, alpha, _tmp_3, _tmp_4, _tmp_5, _tmp_6);
  } else if (((((((((nrhs == 7) && isElement<float>(prhs[0])) && isSide(prhs[1])) && isUplo(prhs[2])) && isDiag(prhs[3])) && isElement<float>(prhs[4])) && isMatrix<float>(prhs[5])) && isMatrix<float>(prhs[6]))) {
    float p = getElement<float>(prhs[0]);
    FFLAS_C_SIDE S = getSide(prhs[1]);
    FFLAS_C_UPLO U = getUplo(prhs[2]);
    FFLAS_C_DIAG D = getDiag(prhs[3]);
    float alpha = getElement<float>(prhs[4]);
    Matrix<float> A = getMatrix<float>(prhs[5]);
    Matrix<float> B = duplicateMatrix<float>(prhs[6], plhs[0]);
    size_t m = rows(B);
    size_t n = cols(B);
    FFLAS_C_SIDE _tmp_0 = invert(S);
    FFLAS_C_UPLO _tmp_1 = invert(U);
    FFLAS_C_TRANSPOSE _tmp_2 = FflasNoTrans;
    const float* _tmp_3 = constptr(A);
    size_t _tmp_4 = ld(A);
    float* _tmp_5 = ptr(B);
    size_t _tmp_6 = ld(B);
    ff_ftrsm(p, _tmp_0, _tmp_1, _tmp_2, D, n, m, alpha, _tmp_3, _tmp_4, _tmp_5, _tmp_6);
  } else if (((((((((nrhs == 7) && isElement<double>(prhs[0])) && isSide(prhs[1])) && isUplo(prhs[2])) && isDiag(prhs[3])) && isElement<double>(prhs[4])) && isMatrix<double>(prhs[5])) && isMatrix<double>(prhs[6]))) {
    double p = getElement<double>(prhs[0]);
    FFLAS_C_SIDE S = getSide(prhs[1]);
    FFLAS_C_UPLO U = getUplo(prhs[2]);
    FFLAS_C_DIAG D = getDiag(prhs[3]);
    double alpha = getElement<double>(prhs[4]);
    Matrix<double> A = getMatrix<double>(prhs[5]);
    Matrix<double> B = duplicateMatrix<double>(prhs[6], plhs[0]);
    size_t m = rows(B);
    size_t n = cols(B);
    FFLAS_C_SIDE _tmp_0 = invert(S);
    FFLAS_C_UPLO _tmp_1 = invert(U);
    FFLAS_C_TRANSPOSE _tmp_2 = FflasNoTrans;
    const double* _tmp_3 = constptr(A);
    size_t _tmp_4 = ld(A);
    double* _tmp_5 = ptr(B);
    size_t _tmp_6 = ld(B);
    ff_ftrsm(p, _tmp_0, _tmp_1, _tmp_2, D, n, m, alpha, _tmp_3, _tmp_4, _tmp_5, _tmp_6);
  } else {
    error("wrong arguments types (or number) for routine: ftrsm.");
  }
}

