/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_matlab.h"
int ff_ftrsv_0(double, ffintert::FlagUplo, ffintert::FlagTrans, ffintert::FlagDiag, size_t, ffintert::Matrix<double>, size_t, ffintert::Vector<double>, size_t);



/* -------------------------------------------------------------------------- */

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
  if (((((((nrhs == 5) && ffintert::isField(prhs[0])) && ffintert::isUplo(prhs[1])) && ffintert::isDiag(prhs[2])) && (ffintert::isMatrix(prhs[3]) && ffintert::isElement(prhs[3]))) && (ffintert::isVector(prhs[4]) && ffintert::isElement(prhs[4])))) {
    double F = ffintert::getField(prhs[0]);
    ffintert::FlagUplo U = ffintert::getUplo(prhs[1]);
    ffintert::FlagDiag D = ffintert::getDiag(prhs[2]);
    ffintert::Matrix<double> A = ffintert::getMatrix(prhs[3]);
    ffintert::Vector<double> X = ffintert::duplicateVector(prhs[4], plhs[0]);
    size_t n = ffintert::length(X);
    ffintert::check(n, ffintert::rows(A), "n");
    ffintert::check(n, ffintert::cols(A), "n");
    ffintert::FlagUplo _tmp_0 = ffintert::invert(U);
    ffintert::FlagTrans _tmp_1 = ffintert::Trans;
    size_t _tmp_2 = ffintert::ld(A);
    size_t _tmp_3 = ffintert::st(X);
    ff_ftrsv_0(F, _tmp_0, _tmp_1, D, n, A, _tmp_2, X, _tmp_3);
  } else {
    ffintert::error("wrong arguments types (or number) for routine: ftrsv.");
  }  
}

