%FTRSM	Triangular System solve with Matrix.
%
%	FTRSM(F, S, U, D, alpha, A, B)   
%	with:
%		 F: Field
%		 S: Side
%		 U: Uplo
%		 D: Diag
%		 alpha: Element
%		 A: Matrix of Element
%		 B: Matrix of Element
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
