/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 *     Generated by the 'ffinterg' tool (v0.4)
 *
 * ========LICENCE========
 * This file is part of the library FFLAS-FFPACK.
 *
 * FFLAS-FFPACK is free software: you can redistribute it and/or modify
 * it under the terms of the  GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 * ========LICENCE========
 */

#include "ffintert_matlab.h"
using namespace ffintert;

void ff_pfadd(int32_t, size_t, size_t, const int32_t*, size_t, const int32_t*, size_t, int32_t*, size_t, int, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_pfadd(int64_t, size_t, size_t, const int64_t*, size_t, const int64_t*, size_t, int64_t*, size_t, int, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_pfadd(Integer, size_t, size_t, const Integer*, size_t, const Integer*, size_t, Integer*, size_t, int);
void ff_pfadd(float, size_t, size_t, const float*, size_t, const float*, size_t, float*, size_t, int, FP_C_RP = FP_C_RP_ModularBalanced);
void ff_pfadd(double, size_t, size_t, const double*, size_t, const double*, size_t, double*, size_t, int, FP_C_RP = FP_C_RP_ModularBalanced);



/* -------------------------------------------------------------------------- */

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
  if ((((((nrhs == 4) && isElement<int32_t>(prhs[0])) && isMatrix<int32_t>(prhs[1])) && isMatrix<int32_t>(prhs[2])) && isInt(prhs[3]))) {
    int32_t p = getElement<int32_t>(prhs[0]);
    Matrix<int32_t> A = getMatrix<int32_t>(prhs[1]);
    Matrix<int32_t> B = getMatrix<int32_t>(prhs[2]);
    int t = getInt(prhs[3]);
    size_t m = rows(A);
    check(m, rows(B), "m");
    size_t n = cols(A);
    check(n, cols(B), "n");
    Matrix<int32_t> C = createMatrix<int32_t>(plhs[0], m, n);
    const int32_t* _tmp_0 = constptr(A);
    size_t _tmp_1 = ld(A);
    const int32_t* _tmp_2 = constptr(B);
    size_t _tmp_3 = ld(B);
    int32_t* _tmp_4 = ptr(C);
    size_t _tmp_5 = ld(C);
    ff_pfadd(p, n, m, _tmp_0, _tmp_1, _tmp_2, _tmp_3, _tmp_4, _tmp_5, t);
  } else if ((((((nrhs == 4) && isElement<int64_t>(prhs[0])) && isMatrix<int64_t>(prhs[1])) && isMatrix<int64_t>(prhs[2])) && isInt(prhs[3]))) {
    int64_t p = getElement<int64_t>(prhs[0]);
    Matrix<int64_t> A = getMatrix<int64_t>(prhs[1]);
    Matrix<int64_t> B = getMatrix<int64_t>(prhs[2]);
    int t = getInt(prhs[3]);
    size_t m = rows(A);
    check(m, rows(B), "m");
    size_t n = cols(A);
    check(n, cols(B), "n");
    Matrix<int64_t> C = createMatrix<int64_t>(plhs[0], m, n);
    const int64_t* _tmp_0 = constptr(A);
    size_t _tmp_1 = ld(A);
    const int64_t* _tmp_2 = constptr(B);
    size_t _tmp_3 = ld(B);
    int64_t* _tmp_4 = ptr(C);
    size_t _tmp_5 = ld(C);
    ff_pfadd(p, n, m, _tmp_0, _tmp_1, _tmp_2, _tmp_3, _tmp_4, _tmp_5, t);
  } else if ((((((nrhs == 4) && isElement<float>(prhs[0])) && isMatrix<float>(prhs[1])) && isMatrix<float>(prhs[2])) && isInt(prhs[3]))) {
    float p = getElement<float>(prhs[0]);
    Matrix<float> A = getMatrix<float>(prhs[1]);
    Matrix<float> B = getMatrix<float>(prhs[2]);
    int t = getInt(prhs[3]);
    size_t m = rows(A);
    check(m, rows(B), "m");
    size_t n = cols(A);
    check(n, cols(B), "n");
    Matrix<float> C = createMatrix<float>(plhs[0], m, n);
    const float* _tmp_0 = constptr(A);
    size_t _tmp_1 = ld(A);
    const float* _tmp_2 = constptr(B);
    size_t _tmp_3 = ld(B);
    float* _tmp_4 = ptr(C);
    size_t _tmp_5 = ld(C);
    ff_pfadd(p, n, m, _tmp_0, _tmp_1, _tmp_2, _tmp_3, _tmp_4, _tmp_5, t);
  } else if ((((((nrhs == 4) && isElement<double>(prhs[0])) && isMatrix<double>(prhs[1])) && isMatrix<double>(prhs[2])) && isInt(prhs[3]))) {
    double p = getElement<double>(prhs[0]);
    Matrix<double> A = getMatrix<double>(prhs[1]);
    Matrix<double> B = getMatrix<double>(prhs[2]);
    int t = getInt(prhs[3]);
    size_t m = rows(A);
    check(m, rows(B), "m");
    size_t n = cols(A);
    check(n, cols(B), "n");
    Matrix<double> C = createMatrix<double>(plhs[0], m, n);
    const double* _tmp_0 = constptr(A);
    size_t _tmp_1 = ld(A);
    const double* _tmp_2 = constptr(B);
    size_t _tmp_3 = ld(B);
    double* _tmp_4 = ptr(C);
    size_t _tmp_5 = ld(C);
    ff_pfadd(p, n, m, _tmp_0, _tmp_1, _tmp_2, _tmp_3, _tmp_4, _tmp_5, t);
  } else {
    error("wrong arguments types (or number) for routine: pfadd.");
  }
}

