%PFSUB	Compute element-wise modular subtraction (in parallel)
%
%	PFSUB(F, A, B, t)   is the element-wise modular subtraction of matrices A and B.
%	with:
%		 F: Field
%		 A: Matrix of Element
%		 B: Matrix of Element
%		 t: Int
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the fflaswg tool
