%PFSUB	Compute element-wise modular subtraction (in parallel)
%
%	PFSUB(p, A, B, t)   is the element-wise modular subtraction of matrices A and B.
%	with:
%		 p: Element of Field 0x1704620
%		 A: Matrix
%		 B: Matrix
%		 t: Int
%

%   Copyright (c) 2015-2016 SILKAN - Granted by the ANR Project HPAC
%   Automatically generated by the ffinter tool
%
%   This file is part of the library FFLAS-FFPACK.
%
%   FFLAS-FFPACK is free software: you can redistribute it and/or modify
%   it under the terms of the  GNU Lesser General Public
%   License as published by the Free Software Foundation; either
%   version 2.1 of the License, or (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%   Lesser General Public License for more details.
%
%   You should have received a copy of the GNU Lesser General Public
%   License along with this library; if not, write to the Free Software
%   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


