/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

int ff_ftrsv_0(double F, ffintert::FlagUplo U, ffintert::FlagTrans _tmp2, ffintert::FlagDiag D, size_t n, ffintert::Matrix<double> A, size_t _tmp6, ffintert::Vector<double> X, size_t _tmp8)
{
  Givaro::ModularBalanced<double> _tmp0 = ffintert::toField(F);
  FFLAS::FFLAS_UPLO _tmp1 = ffintert::toUplo(U);
  FFLAS::FFLAS_TRANSPOSE _tmp3 = ffintert::toOrientation(_tmp2);
  FFLAS::FFLAS_DIAG _tmp4 = ffintert::toDiag(D);
  Givaro::ModularBalanced<double>::Element* _tmp5 = ffintert::toMatrix(A);
  Givaro::ModularBalanced<double>::Element* _tmp7 = ffintert::toVector(X);
  FFLAS::ftrsv(_tmp0, _tmp1, _tmp3, _tmp4, n, _tmp5, _tmp6, _tmp7, _tmp8);
}

