/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

int ff_fsquare_0(double F, ffintert::FlagTrans _tmp1, size_t n, double alpha, ffintert::Matrix<double> A, size_t _tmp5, double beta, ffintert::Matrix<double> C, size_t _tmp8)
{
  Givaro::ModularBalanced<double> _tmp0 = ffintert::toField(F);
  FFLAS::FFLAS_TRANSPOSE _tmp2 = ffintert::toOrientation(_tmp1);
  Givaro::ModularBalanced<double>::Element _tmp3 = ffintert::toElement(alpha);
  Givaro::ModularBalanced<double>::Element* _tmp4 = ffintert::toMatrix(A);
  Givaro::ModularBalanced<double>::Element _tmp6 = ffintert::toElement(beta);
  Givaro::ModularBalanced<double>::Element* _tmp7 = ffintert::toMatrix(C);
  FFLAS::fsquare(_tmp0, _tmp2, n, _tmp3, _tmp4, _tmp5, _tmp6, _tmp7, _tmp8);
}

