/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 *     Generated by the 'ffinterg' tool (v0.4)
 *
 * ========LICENCE========
 * This file is part of the library FFLAS-FFPACK.
 *
 * FFLAS-FFPACK is free software: you can redistribute it and/or modify
 * it under the terms of the  GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 * ========LICENCE========
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

using namespace FFLAS;
using namespace Givaro;
/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

int32_t ff_fdot(int32_t p, size_t n, const int32_t* _tmp0, size_t _tmp1, int32_t* _tmp2, size_t _tmp3, FP_C_RP fp_rp)
{
  int32_t Z = 0;
  if ((fp_rp == FP_C_RP_Modular)) {
    Z = fdot(Modular<int32_t>(p), n, Modular<int32_t>::ConstElement_ptr(_tmp0), _tmp1, Modular<int32_t>::Element_ptr(_tmp2), _tmp3);
    return Z;
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    Z = fdot(ModularBalanced<int32_t>(p), n, ModularBalanced<int32_t>::ConstElement_ptr(_tmp0), _tmp1, ModularBalanced<int32_t>::Element_ptr(_tmp2), _tmp3);
    return Z;
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
  return Z;
}


/* -------------------------------------------------------------------------- */

int64_t ff_fdot(int64_t p, size_t n, const int64_t* _tmp0, size_t _tmp1, int64_t* _tmp2, size_t _tmp3, FP_C_RP fp_rp)
{
  int64_t Z = 0;
  if ((fp_rp == FP_C_RP_Modular)) {
    Z = fdot(Modular<int64_t>(p), n, Modular<int64_t>::ConstElement_ptr(_tmp0), _tmp1, Modular<int64_t>::Element_ptr(_tmp2), _tmp3);
    return Z;
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    Z = fdot(ModularBalanced<int64_t>(p), n, ModularBalanced<int64_t>::ConstElement_ptr(_tmp0), _tmp1, ModularBalanced<int64_t>::Element_ptr(_tmp2), _tmp3);
    return Z;
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
  return Z;
}


/* -------------------------------------------------------------------------- */

Integer ff_fdot(Integer p, size_t n, const Integer* _tmp0, size_t _tmp1, Integer* _tmp2, size_t _tmp3)
{
  Integer Z = fdot(Modular<Integer>(p), n, Modular<Integer>::ConstElement_ptr(_tmp0), _tmp1, Modular<Integer>::Element_ptr(_tmp2), _tmp3);
  return Z;
}


/* -------------------------------------------------------------------------- */

float ff_fdot(float p, size_t n, const float* _tmp0, size_t _tmp1, float* _tmp2, size_t _tmp3, FP_C_RP fp_rp)
{
  float Z = 0;
  if ((fp_rp == FP_C_RP_Modular)) {
    Z = fdot(Modular<float>(p), n, Modular<float>::ConstElement_ptr(_tmp0), _tmp1, Modular<float>::Element_ptr(_tmp2), _tmp3);
    return Z;
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    Z = fdot(ModularBalanced<float>(p), n, ModularBalanced<float>::ConstElement_ptr(_tmp0), _tmp1, ModularBalanced<float>::Element_ptr(_tmp2), _tmp3);
    return Z;
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
  return Z;
}


/* -------------------------------------------------------------------------- */

double ff_fdot(double p, size_t n, const double* _tmp0, size_t _tmp1, double* _tmp2, size_t _tmp3, FP_C_RP fp_rp)
{
  double Z = 0;
  if ((fp_rp == FP_C_RP_Modular)) {
    Z = fdot(Modular<double>(p), n, Modular<double>::ConstElement_ptr(_tmp0), _tmp1, Modular<double>::Element_ptr(_tmp2), _tmp3);
    return Z;
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    Z = fdot(ModularBalanced<double>(p), n, ModularBalanced<double>::ConstElement_ptr(_tmp0), _tmp1, ModularBalanced<double>::Element_ptr(_tmp2), _tmp3);
    return Z;
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
  return Z;
}

