/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

int ff_fgemv_0(double F, ffintert::FlagTrans _tmp1, size_t m, size_t n, double alpha, ffintert::Matrix<double> A, size_t _tmp5, ffintert::Vector<double> X, size_t _tmp7, double beta, ffintert::Vector<double> Y, size_t _tmp10)
{
  Givaro::ModularBalanced<double> _tmp0 = ffintert::toField(F);
  FFLAS::FFLAS_TRANSPOSE _tmp2 = ffintert::toOrientation(_tmp1);
  Givaro::ModularBalanced<double>::Element _tmp3 = ffintert::toElement(alpha);
  Givaro::ModularBalanced<double>::Element* _tmp4 = ffintert::toMatrix(A);
  Givaro::ModularBalanced<double>::Element* _tmp6 = ffintert::toVector(X);
  Givaro::ModularBalanced<double>::Element _tmp8 = ffintert::toElement(beta);
  Givaro::ModularBalanced<double>::Element* _tmp9 = ffintert::toVector(Y);
  FFLAS::fgemv(_tmp0, _tmp2, m, n, _tmp3, _tmp4, _tmp5, _tmp6, _tmp7, _tmp8, _tmp9, _tmp10);
}

