/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

bool ff_fiszero_0(double F, size_t n, ffintert::Vector<double> X, size_t _tmp2)
{
  Givaro::ModularBalanced<double> _tmp0 = ffintert::toField(F);
  Givaro::ModularBalanced<double>::Element* _tmp1 = ffintert::toVector(X);
  bool b = FFLAS::fiszero(_tmp0, n, _tmp1, _tmp2);
  return b;
}


/* -------------------------------------------------------------------------- */

bool ff_fiszero_1(double F, size_t m, size_t n, ffintert::Matrix<double> A, size_t _tmp2)
{
  Givaro::ModularBalanced<double> _tmp0 = ffintert::toField(F);
  Givaro::ModularBalanced<double>::Element* _tmp1 = ffintert::toMatrix(A);
  bool b = FFLAS::fiszero(_tmp0, m, n, _tmp1, _tmp2);
  return b;
}

