/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

bool ff_fequal_0(double F, size_t n, ffintert::Vector<double> X, size_t _tmp2, ffintert::Vector<double> Y, size_t _tmp4)
{
  Givaro::ModularBalanced<double> _tmp0 = ffintert::toField(F);
  Givaro::ModularBalanced<double>::Element* _tmp1 = ffintert::toVector(X);
  Givaro::ModularBalanced<double>::Element* _tmp3 = ffintert::toVector(Y);
  bool b = FFLAS::fequal(_tmp0, n, _tmp1, _tmp2, _tmp3, _tmp4);
  return b;
}


/* -------------------------------------------------------------------------- */

bool ff_fequal_1(double F, size_t m, size_t n, ffintert::Matrix<double> A, size_t _tmp2, ffintert::Matrix<double> B, size_t _tmp4)
{
  Givaro::ModularBalanced<double> _tmp0 = ffintert::toField(F);
  Givaro::ModularBalanced<double>::Element* _tmp1 = ffintert::toMatrix(A);
  Givaro::ModularBalanced<double>::Element* _tmp3 = ffintert::toMatrix(B);
  bool b = FFLAS::fequal(_tmp0, m, n, _tmp1, _tmp2, _tmp3, _tmp4);
  return b;
}

