/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

int ff_ftrmm_0(double F, ffintert::FlagSide S, ffintert::FlagUplo U, ffintert::FlagTrans T, ffintert::FlagDiag D, size_t m, size_t n, double alpha, ffintert::Matrix<double> A, size_t _tmp7, ffintert::Matrix<double> B, size_t _tmp9)
{
  Givaro::ModularBalanced<double> _tmp0 = ffintert::toField(F);
  FFLAS::FFLAS_SIDE _tmp1 = ffintert::toSide(S);
  FFLAS::FFLAS_UPLO _tmp2 = ffintert::toUplo(U);
  FFLAS::FFLAS_TRANSPOSE _tmp3 = ffintert::toOrientation(T);
  FFLAS::FFLAS_DIAG _tmp4 = ffintert::toDiag(D);
  Givaro::ModularBalanced<double>::Element _tmp5 = ffintert::toElement(alpha);
  Givaro::ModularBalanced<double>::Element* _tmp6 = ffintert::toMatrix(A);
  Givaro::ModularBalanced<double>::Element* _tmp8 = ffintert::toMatrix(B);
  FFLAS::ftrmm(_tmp0, _tmp1, _tmp2, _tmp3, _tmp4, m, n, _tmp5, _tmp6, _tmp7, _tmp8, _tmp9);
}

