/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

int ff_fgemm_0(double F, ffintert::FlagTrans _tmp1, ffintert::FlagTrans _tmp3, size_t m, size_t n, size_t k, double alpha, ffintert::Matrix<double> A, size_t _tmp7, ffintert::Matrix<double> B, size_t _tmp9, double beta, ffintert::Matrix<double> C, size_t _tmp12)
{
  Givaro::ModularBalanced<double> _tmp0 = ffintert::toField(F);
  FFLAS::FFLAS_TRANSPOSE _tmp2 = ffintert::toOrientation(_tmp1);
  FFLAS::FFLAS_TRANSPOSE _tmp4 = ffintert::toOrientation(_tmp3);
  Givaro::ModularBalanced<double>::Element _tmp5 = ffintert::toElement(alpha);
  Givaro::ModularBalanced<double>::Element* _tmp6 = ffintert::toMatrix(A);
  Givaro::ModularBalanced<double>::Element* _tmp8 = ffintert::toMatrix(B);
  Givaro::ModularBalanced<double>::Element _tmp10 = ffintert::toElement(beta);
  Givaro::ModularBalanced<double>::Element* _tmp11 = ffintert::toMatrix(C);
  FFLAS::fgemm(_tmp0, _tmp2, _tmp4, m, n, k, _tmp5, _tmp6, _tmp7, _tmp8, _tmp9, _tmp10, _tmp11, _tmp12);
}

