/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 *     Generated by the 'ffinterg' tool (v0.4)
 *
 * ========LICENCE========
 * This file is part of the library FFLAS-FFPACK.
 *
 * FFLAS-FFPACK is free software: you can redistribute it and/or modify
 * it under the terms of the  GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 * ========LICENCE========
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

using namespace FFLAS;
using namespace Givaro;
/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

void ff_fgemm(int32_t p, FFLAS_C_TRANSPOSE _tmp0, FFLAS_C_TRANSPOSE _tmp1, size_t m, size_t n, size_t k, int32_t alpha, const int32_t* _tmp2, size_t _tmp3, const int32_t* _tmp4, size_t _tmp5, int32_t beta, int32_t* _tmp6, size_t _tmp7, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    fgemm(Modular<int32_t>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_TRANSPOSE) (_tmp1), m, n, k, (alpha), Modular<int32_t>::ConstElement_ptr(_tmp2), _tmp3, Modular<int32_t>::ConstElement_ptr(_tmp4), _tmp5, (beta), Modular<int32_t>::Element_ptr(_tmp6), _tmp7);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    fgemm(ModularBalanced<int32_t>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_TRANSPOSE) (_tmp1), m, n, k, (alpha), ModularBalanced<int32_t>::ConstElement_ptr(_tmp2), _tmp3, ModularBalanced<int32_t>::ConstElement_ptr(_tmp4), _tmp5, (beta), ModularBalanced<int32_t>::Element_ptr(_tmp6), _tmp7);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}


/* -------------------------------------------------------------------------- */

void ff_fgemm(int64_t p, FFLAS_C_TRANSPOSE _tmp0, FFLAS_C_TRANSPOSE _tmp1, size_t m, size_t n, size_t k, int64_t alpha, const int64_t* _tmp2, size_t _tmp3, const int64_t* _tmp4, size_t _tmp5, int64_t beta, int64_t* _tmp6, size_t _tmp7, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    fgemm(Modular<int64_t>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_TRANSPOSE) (_tmp1), m, n, k, (alpha), Modular<int64_t>::ConstElement_ptr(_tmp2), _tmp3, Modular<int64_t>::ConstElement_ptr(_tmp4), _tmp5, (beta), Modular<int64_t>::Element_ptr(_tmp6), _tmp7);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    fgemm(ModularBalanced<int64_t>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_TRANSPOSE) (_tmp1), m, n, k, (alpha), ModularBalanced<int64_t>::ConstElement_ptr(_tmp2), _tmp3, ModularBalanced<int64_t>::ConstElement_ptr(_tmp4), _tmp5, (beta), ModularBalanced<int64_t>::Element_ptr(_tmp6), _tmp7);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}


/* -------------------------------------------------------------------------- */

void ff_fgemm(Integer p, FFLAS_C_TRANSPOSE _tmp0, FFLAS_C_TRANSPOSE _tmp1, size_t m, size_t n, size_t k, Integer alpha, const Integer* _tmp2, size_t _tmp3, const Integer* _tmp4, size_t _tmp5, Integer beta, Integer* _tmp6, size_t _tmp7)
{
  fgemm(Modular<Integer>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_TRANSPOSE) (_tmp1), m, n, k, (alpha), Modular<Integer>::ConstElement_ptr(_tmp2), _tmp3, Modular<Integer>::ConstElement_ptr(_tmp4), _tmp5, (beta), Modular<Integer>::Element_ptr(_tmp6), _tmp7);
}


/* -------------------------------------------------------------------------- */

void ff_fgemm(float p, FFLAS_C_TRANSPOSE _tmp0, FFLAS_C_TRANSPOSE _tmp1, size_t m, size_t n, size_t k, float alpha, const float* _tmp2, size_t _tmp3, const float* _tmp4, size_t _tmp5, float beta, float* _tmp6, size_t _tmp7, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    fgemm(Modular<float>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_TRANSPOSE) (_tmp1), m, n, k, (alpha), Modular<float>::ConstElement_ptr(_tmp2), _tmp3, Modular<float>::ConstElement_ptr(_tmp4), _tmp5, (beta), Modular<float>::Element_ptr(_tmp6), _tmp7);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    fgemm(ModularBalanced<float>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_TRANSPOSE) (_tmp1), m, n, k, (alpha), ModularBalanced<float>::ConstElement_ptr(_tmp2), _tmp3, ModularBalanced<float>::ConstElement_ptr(_tmp4), _tmp5, (beta), ModularBalanced<float>::Element_ptr(_tmp6), _tmp7);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}


/* -------------------------------------------------------------------------- */

void ff_fgemm(double p, FFLAS_C_TRANSPOSE _tmp0, FFLAS_C_TRANSPOSE _tmp1, size_t m, size_t n, size_t k, double alpha, const double* _tmp2, size_t _tmp3, const double* _tmp4, size_t _tmp5, double beta, double* _tmp6, size_t _tmp7, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    fgemm(Modular<double>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_TRANSPOSE) (_tmp1), m, n, k, (alpha), Modular<double>::ConstElement_ptr(_tmp2), _tmp3, Modular<double>::ConstElement_ptr(_tmp4), _tmp5, (beta), Modular<double>::Element_ptr(_tmp6), _tmp7);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    fgemm(ModularBalanced<double>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_TRANSPOSE) (_tmp1), m, n, k, (alpha), ModularBalanced<double>::ConstElement_ptr(_tmp2), _tmp3, ModularBalanced<double>::ConstElement_ptr(_tmp4), _tmp5, (beta), ModularBalanced<double>::Element_ptr(_tmp6), _tmp7);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}

