/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 *     Generated by the 'ffinterg' tool (v0.4)
 *
 * ========LICENCE========
 * This file is part of the library FFLAS-FFPACK.
 *
 * FFLAS-FFPACK is free software: you can redistribute it and/or modify
 * it under the terms of the  GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 * ========LICENCE========
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

using namespace FFLAS;
using namespace Givaro;
/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

void ff_ftrsv(int32_t p, FFLAS_C_UPLO U, FFLAS_C_TRANSPOSE _tmp0, FFLAS_C_DIAG D, size_t n, const int32_t* _tmp1, size_t _tmp2, int32_t* _tmp3, size_t _tmp4, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    ftrsv(Modular<int32_t>(p), (FFLAS::FFLAS_UPLO) (U), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_DIAG) (D), n, Modular<int32_t>::ConstElement_ptr(_tmp1), _tmp2, Modular<int32_t>::Element_ptr(_tmp3), _tmp4);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    ftrsv(ModularBalanced<int32_t>(p), (FFLAS::FFLAS_UPLO) (U), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_DIAG) (D), n, ModularBalanced<int32_t>::ConstElement_ptr(_tmp1), _tmp2, ModularBalanced<int32_t>::Element_ptr(_tmp3), _tmp4);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}


/* -------------------------------------------------------------------------- */

void ff_ftrsv(int64_t p, FFLAS_C_UPLO U, FFLAS_C_TRANSPOSE _tmp0, FFLAS_C_DIAG D, size_t n, const int64_t* _tmp1, size_t _tmp2, int64_t* _tmp3, size_t _tmp4, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    ftrsv(Modular<int64_t>(p), (FFLAS::FFLAS_UPLO) (U), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_DIAG) (D), n, Modular<int64_t>::ConstElement_ptr(_tmp1), _tmp2, Modular<int64_t>::Element_ptr(_tmp3), _tmp4);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    ftrsv(ModularBalanced<int64_t>(p), (FFLAS::FFLAS_UPLO) (U), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_DIAG) (D), n, ModularBalanced<int64_t>::ConstElement_ptr(_tmp1), _tmp2, ModularBalanced<int64_t>::Element_ptr(_tmp3), _tmp4);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}


/* -------------------------------------------------------------------------- */

void ff_ftrsv(Integer p, FFLAS_C_UPLO U, FFLAS_C_TRANSPOSE _tmp0, FFLAS_C_DIAG D, size_t n, const Integer* _tmp1, size_t _tmp2, Integer* _tmp3, size_t _tmp4)
{
  ftrsv(Modular<Integer>(p), (FFLAS::FFLAS_UPLO) (U), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_DIAG) (D), n, Modular<Integer>::ConstElement_ptr(_tmp1), _tmp2, Modular<Integer>::Element_ptr(_tmp3), _tmp4);
}


/* -------------------------------------------------------------------------- */

void ff_ftrsv(float p, FFLAS_C_UPLO U, FFLAS_C_TRANSPOSE _tmp0, FFLAS_C_DIAG D, size_t n, const float* _tmp1, size_t _tmp2, float* _tmp3, size_t _tmp4, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    ftrsv(Modular<float>(p), (FFLAS::FFLAS_UPLO) (U), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_DIAG) (D), n, Modular<float>::ConstElement_ptr(_tmp1), _tmp2, Modular<float>::Element_ptr(_tmp3), _tmp4);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    ftrsv(ModularBalanced<float>(p), (FFLAS::FFLAS_UPLO) (U), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_DIAG) (D), n, ModularBalanced<float>::ConstElement_ptr(_tmp1), _tmp2, ModularBalanced<float>::Element_ptr(_tmp3), _tmp4);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}


/* -------------------------------------------------------------------------- */

void ff_ftrsv(double p, FFLAS_C_UPLO U, FFLAS_C_TRANSPOSE _tmp0, FFLAS_C_DIAG D, size_t n, const double* _tmp1, size_t _tmp2, double* _tmp3, size_t _tmp4, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    ftrsv(Modular<double>(p), (FFLAS::FFLAS_UPLO) (U), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_DIAG) (D), n, Modular<double>::ConstElement_ptr(_tmp1), _tmp2, Modular<double>::Element_ptr(_tmp3), _tmp4);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    ftrsv(ModularBalanced<double>(p), (FFLAS::FFLAS_UPLO) (U), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), (FFLAS::FFLAS_DIAG) (D), n, ModularBalanced<double>::ConstElement_ptr(_tmp1), _tmp2, ModularBalanced<double>::Element_ptr(_tmp3), _tmp4);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}

