/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 *     Generated by the 'ffinterg' tool (v0.4)
 *
 * ========LICENCE========
 * This file is part of the library FFLAS-FFPACK.
 *
 * FFLAS-FFPACK is free software: you can redistribute it and/or modify
 * it under the terms of the  GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 * ========LICENCE========
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

using namespace FFLAS;
using namespace Givaro;
/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

void ff_fgemv(int32_t p, FFLAS_C_TRANSPOSE _tmp0, size_t m, size_t n, int32_t alpha, const int32_t* _tmp1, size_t _tmp2, const int32_t* _tmp3, size_t _tmp4, int32_t beta, int32_t* _tmp5, size_t _tmp6, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    fgemv(Modular<int32_t>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), m, n, (alpha), Modular<int32_t>::ConstElement_ptr(_tmp1), _tmp2, Modular<int32_t>::ConstElement_ptr(_tmp3), _tmp4, (beta), Modular<int32_t>::Element_ptr(_tmp5), _tmp6);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    fgemv(ModularBalanced<int32_t>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), m, n, (alpha), ModularBalanced<int32_t>::ConstElement_ptr(_tmp1), _tmp2, ModularBalanced<int32_t>::ConstElement_ptr(_tmp3), _tmp4, (beta), ModularBalanced<int32_t>::Element_ptr(_tmp5), _tmp6);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}


/* -------------------------------------------------------------------------- */

void ff_fgemv(int64_t p, FFLAS_C_TRANSPOSE _tmp0, size_t m, size_t n, int64_t alpha, const int64_t* _tmp1, size_t _tmp2, const int64_t* _tmp3, size_t _tmp4, int64_t beta, int64_t* _tmp5, size_t _tmp6, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    fgemv(Modular<int64_t>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), m, n, (alpha), Modular<int64_t>::ConstElement_ptr(_tmp1), _tmp2, Modular<int64_t>::ConstElement_ptr(_tmp3), _tmp4, (beta), Modular<int64_t>::Element_ptr(_tmp5), _tmp6);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    fgemv(ModularBalanced<int64_t>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), m, n, (alpha), ModularBalanced<int64_t>::ConstElement_ptr(_tmp1), _tmp2, ModularBalanced<int64_t>::ConstElement_ptr(_tmp3), _tmp4, (beta), ModularBalanced<int64_t>::Element_ptr(_tmp5), _tmp6);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}


/* -------------------------------------------------------------------------- */

void ff_fgemv(Integer p, FFLAS_C_TRANSPOSE _tmp0, size_t m, size_t n, Integer alpha, const Integer* _tmp1, size_t _tmp2, const Integer* _tmp3, size_t _tmp4, Integer beta, Integer* _tmp5, size_t _tmp6)
{
  fgemv(Modular<Integer>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), m, n, (alpha), Modular<Integer>::ConstElement_ptr(_tmp1), _tmp2, Modular<Integer>::ConstElement_ptr(_tmp3), _tmp4, (beta), Modular<Integer>::Element_ptr(_tmp5), _tmp6);
}


/* -------------------------------------------------------------------------- */

void ff_fgemv(float p, FFLAS_C_TRANSPOSE _tmp0, size_t m, size_t n, float alpha, const float* _tmp1, size_t _tmp2, const float* _tmp3, size_t _tmp4, float beta, float* _tmp5, size_t _tmp6, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    fgemv(Modular<float>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), m, n, (alpha), Modular<float>::ConstElement_ptr(_tmp1), _tmp2, Modular<float>::ConstElement_ptr(_tmp3), _tmp4, (beta), Modular<float>::Element_ptr(_tmp5), _tmp6);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    fgemv(ModularBalanced<float>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), m, n, (alpha), ModularBalanced<float>::ConstElement_ptr(_tmp1), _tmp2, ModularBalanced<float>::ConstElement_ptr(_tmp3), _tmp4, (beta), ModularBalanced<float>::Element_ptr(_tmp5), _tmp6);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}


/* -------------------------------------------------------------------------- */

void ff_fgemv(double p, FFLAS_C_TRANSPOSE _tmp0, size_t m, size_t n, double alpha, const double* _tmp1, size_t _tmp2, const double* _tmp3, size_t _tmp4, double beta, double* _tmp5, size_t _tmp6, FP_C_RP fp_rp)
{
  if ((fp_rp == FP_C_RP_Modular)) {
    fgemv(Modular<double>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), m, n, (alpha), Modular<double>::ConstElement_ptr(_tmp1), _tmp2, Modular<double>::ConstElement_ptr(_tmp3), _tmp4, (beta), Modular<double>::Element_ptr(_tmp5), _tmp6);
  } else if ((fp_rp == FP_C_RP_ModularBalanced)) {
    fgemv(ModularBalanced<double>(p), (FFLAS::FFLAS_TRANSPOSE) (_tmp0), m, n, (alpha), ModularBalanced<double>::ConstElement_ptr(_tmp1), _tmp2, ModularBalanced<double>::ConstElement_ptr(_tmp3), _tmp4, (beta), ModularBalanced<double>::Element_ptr(_tmp5), _tmp6);
  } else {
    throw std::runtime_error("wrong field representation parameter.");
  }
}

