/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

#include "ffintert_cxx.h"
#include "fflas-ffpack/fflas/fflas.h"

/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */

int ff_fger_0(double F, size_t m, size_t n, double alpha, ffintert::Vector<double> X, size_t _tmp3, ffintert::Vector<double> Y, size_t _tmp5, ffintert::Matrix<double> A, size_t _tmp7)
{
  Givaro::ModularBalanced<double> _tmp0 = ffintert::toField(F);
  Givaro::ModularBalanced<double>::Element _tmp1 = ffintert::toElement(alpha);
  Givaro::ModularBalanced<double>::Element* _tmp2 = ffintert::toVector(X);
  Givaro::ModularBalanced<double>::Element* _tmp4 = ffintert::toVector(Y);
  Givaro::ModularBalanced<double>::Element* _tmp6 = ffintert::toMatrix(A);
  FFLAS::fger(_tmp0, m, n, _tmp1, _tmp2, _tmp3, _tmp4, _tmp5, _tmp6, _tmp7);
}

