/* ------------------------------------------------------------------ -*- c++ -*-
 *
 * (c) SILKAN           - 2014-2016
 * (c) ANR Project HPAC -  Generated by the 'ffinterg' tool (v0.4)
 *
 */

int ff_fadd_0(double, size_t, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t);
int ff_fadd_1(double, size_t, size_t, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t);
int ff_fadd_2(double, size_t, ffintert::Vector<double>, size_t, double, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t);
int ff_fadd_3(double, size_t, size_t, ffintert::Matrix<double>, size_t, double, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t);
int ff_faxpy_0(double, size_t, double, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t);
int ff_faxpy_1(double, size_t, size_t, double, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t);
double ff_fdot_0(double, size_t, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t);
bool ff_fequal_0(double, size_t, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t);
bool ff_fequal_1(double, size_t, size_t, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t);
int ff_fgemm_0(double, ffintert::FlagTrans, ffintert::FlagTrans, size_t, size_t, size_t, double, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t, double, ffintert::Matrix<double>, size_t);
int ff_fgemv_0(double, ffintert::FlagTrans, size_t, size_t, double, ffintert::Matrix<double>, size_t, ffintert::Vector<double>, size_t, double, ffintert::Vector<double>, size_t);
int ff_fger_0(double, size_t, size_t, double, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t, ffintert::Matrix<double>, size_t);
bool ff_fiszero_0(double, size_t, ffintert::Vector<double>, size_t);
bool ff_fiszero_1(double, size_t, size_t, ffintert::Matrix<double>, size_t);
int ff_fneg_0(double, size_t, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t);
int ff_fneg_1(double, size_t, size_t, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t);
int ff_freduce_0(double, size_t, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t);
int ff_freduce_1(double, size_t, size_t, ffintert::Matrix<double>, size_t);
int ff_fscal_0(double, size_t, double, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t);
int ff_fscal_1(double, size_t, size_t, double, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t);
int ff_fsquare_0(double, ffintert::FlagTrans, size_t, double, ffintert::Matrix<double>, size_t, double, ffintert::Matrix<double>, size_t);
int ff_fsub_0(double, size_t, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t, ffintert::Vector<double>, size_t);
int ff_fsub_1(double, size_t, size_t, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t);
int ff_ftrmm_0(double, ffintert::FlagSide, ffintert::FlagUplo, ffintert::FlagTrans, ffintert::FlagDiag, size_t, size_t, double, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t);
int ff_ftrsm_0(double, ffintert::FlagSide, ffintert::FlagUplo, ffintert::FlagTrans, ffintert::FlagDiag, size_t, size_t, double, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t);
int ff_ftrsv_0(double, ffintert::FlagUplo, ffintert::FlagTrans, ffintert::FlagDiag, size_t, ffintert::Matrix<double>, size_t, ffintert::Vector<double>, size_t);
int ff_pfadd_0(double, size_t, size_t, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t, int);
int ff_pfsub_0(double, size_t, size_t, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t, ffintert::Matrix<double>, size_t, int);
