.TH FFLAS-FFPACK-CONFIG "1" "June 2012" "fflas-ffpack-config" "User Commands"
.SH NAME
fflas-ffpack-config \- configuration tool for FFLAS-FFPACK
.SH SYNOPSIS
.B fflas-ffpack-config
[\fIOPTION\fR]
.SH DESCRIPTION
Known values for OPTION are:
.TP
\fB\-\-prefix\fR
show Givaro installation prefix
.TP
\fB\-\-libs\fR
print library linking information
.TP
\fB\-\-blas\-libs\fR
print BLAS library linking information
.TP
\fB\-\-cflags\fR
print pre\-processor and compiler flags
.TP
\fB\-\-blas\-cflags\fR
print BLAS pre\-processor and BLAS compiler flags
.TP
\fB\-\-blas\-home\fR
print where BLAS were found
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information string (eg 1.6.0)
.TP
\fB\-\-decimal\-version\fR
output version in decimal representation (base 100, that is 10600)
.SH AUTHOR
This manual page was written by Lifeng Sun <lifongsun@gmail.com> for
the Debian system (but may be used by others).
