#ifndef __FFLASFFPACK_optimise_H
#define __FFLASFFPACK_optimise_H

#ifndef __FFLASFFPACK_WINOTHRESHOLD
#define __FFLASFFPACK_WINOTHRESHOLD 1896
#endif

#ifndef __FFLASFFPACK_WINOTHRESHOLD_FLT
#define __FFLASFFPACK_WINOTHRESHOLD_FLT 2408
#endif

#endif // optimise.h
